name: from slack
env:
  REPO_OWNER: Noman46
  REPO_NAME: git_slack_intg
  GITHUB_TOKEN: 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
on:
  repository_dispatch:
    types: [from_slack]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Ping
        run: npm run ping
