name: from slack
env:
  REPO_OWNER: Noman46
  REPO_NAME: git_slack_intg
  GITHUB_TOKEN: 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
on:
  repository_dispatch:
    types: [from_slack]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Ping
        run: npm run ping
